# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-21 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name=b'\xe8\xa7\x92\xe8\x89\xb2\xe5\x90\x8d')),
                ('zh_name', models.CharField(max_length=100, verbose_name=b'\xe8\xa7\x92\xe8\x89\xb2\xe4\xb8\xad\xe6\x96\x87\xe5\x90\x8d')),
                ('desc', models.CharField(blank=True, max_length=500, verbose_name=b'\xe8\xa7\x92\xe8\x89\xb2\xe6\x9d\x83\xe9\x99\x90\xe8\xaf\xb4\xe6\x98\x8e')),
                ('creator', models.CharField(blank=True, max_length=30, verbose_name='\u521b\u5efa\u4eba')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
