# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-21 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('creator', models.CharField(max_length=30, verbose_name='\u521b\u5efa\u4eba')),
                ('work_order_id', models.IntegerField(verbose_name='\u5de5\u5355id')),
                ('flow', models.CharField(blank=True, max_length=10, verbose_name='\u6d41\u7a0b')),
                ('data', models.CharField(max_length=999, verbose_name='\u8868\u5355\u63d0\u4ea4\u6570\u636e')),
                ('state', models.IntegerField(default=1, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('cur_role_id', models.IntegerField(verbose_name='\u5f53\u524d\u5904\u7406\u89d2\u8272id')),
                ('cur_users', models.CharField(blank=True, max_length=999, verbose_name='\u5f53\u524d\u53ef\u5904\u7406\u4eba\u5217\u8868')),
                ('cur_user', models.CharField(blank=True, max_length=30, verbose_name='\u5f53\u524d\u5904\u7406\u4eba')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Task_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(verbose_name='\u4efb\u52a1id')),
                ('username', models.CharField(max_length=30, verbose_name='\u7528\u6237\u540d')),
                ('role_id', models.IntegerField(verbose_name='\u89d2\u8272id')),
                ('act_type', models.IntegerField(default=1, verbose_name='\u5904\u7406\u7c7b\u578b')),
                ('act_opinion', models.TextField(blank=True, max_length=1000, verbose_name='\u5904\u7406\u610f\u89c1\u53cd\u9988')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u8bb0\u5f55\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Work_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u5de5\u5355\u540d(\u82f1\u6587)')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('desc', models.TextField(blank=True, verbose_name='\u63cf\u8ff0')),
                ('flow', models.CharField(blank=True, max_length=10, verbose_name='\u6d41\u7a0b')),
                ('take_time', models.IntegerField(blank=True, default=1, verbose_name='\u64cd\u4f5c\u9700\u8981\u65f6\u95f4')),
                ('is_active', models.IntegerField(default=1, verbose_name='\u662f\u5426\u542f\u7528')),
                ('creator', models.CharField(max_length=30, verbose_name='\u521b\u5efa\u4eba')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
    ]
